### ISSUE TITLE
HA 2023.4 (beta) no longer works with entities calendar

### ISSUE THREAD

**Issue by gateriderz** [gadgetchnnel/entities_calendar#16] opened 2023-03-31 13:24 UTC
Home Assistant Core: 2023.4.0b2
Entities_Calendar: 0.0.9
Breaking Change: https://github.com/home-assistant/core/pull/89533

Since the upgrade of HA 2023.4.0, the calendar update fails when end date is not specified or the same as start.

```
Update for calendar.holidays fails
Update for calendar.vacations fails
Update for calendar.other_events fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 270, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-04 20:00:00-04:00, 2023-04-04 20:00:00-04:00)

```

I was able to temporarily fix this issue by modifying the logic:

```
    async def async_get_events(self, hass, start_date, end_date):
...
            if start and not entity[CONF_END_TIME]:
                # If there is a start time and no end time options are defined
                # also use the start time as the end time
                end = start + timedelta(days=1)  <<<<<<=================
            else:
                end = _get_date(entity[CONF_END_TIME], state_object)

            # If start time and end time are the same
            if end == start:
                end = start + timedelta(days=1)  <<<<<<=================

...
```

**Comment by vlad36N** [comment] 2023-04-06 16:35
After update to HA 2023.4.0
Entities_Calendar: 0.0.9
Added temporarily fix by [gateriderz](https://github.com/gateriderz), but still getting error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 275, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

**Comment by gadgetchnnel** [comment] 2023-04-06 17:52
Can you post your config, and an example of what the state of the entity looks like so I can try too reproduce this?
I'm not seeing that error myself, so this will help with identifying the issue.

**Comment by vlad36N** [comment] 2023-04-06 18:09
Hi,

In configuration.yaml I have:

`calendar: !include include/calendar.yaml`

In calendar.yaml have a lot, but will give you few

```
- platform: entities_calendar
    calendars:
      - name: Medicine
        entities:
          - entity: sensor.event_medicine
            all_day: true
          - entity: sensor.event_medicine_1
            all_day: true
      - name: Appointments
        entities:
          - entity: sensor.event_appointments_ct
          - entity: sensor.event_appointments_echo
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
      - name: Vacation
        entities:
          - entity: sensor.event_vacation_vlad_inna
            all_day: true
          - entity: sensor.event_vacation_vlad_inna_1
            all_day: true
      - name: Classes
        entities:
          - entity: sensor.event_classes_sql
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
          - entity: sensor.event_classes_sql_1
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
```

Have events.yaml file in located in sensor directory

```
  - platform: template
    sensors:
      event_medicine:
        friendly_name: "Vlad vitamin D"
        value_template: "{{ as_timestamp('2021-04-07') | timestamp_local }}"
        device_class: "timestamp"
      event_medicine_1:
        friendly_name: "Vlad vitamin D"
        value_template: "{{ as_timestamp('2021-04-14') | timestamp_local }}"
        device_class: "timestamp"
      event_appointments_ct:
        friendly_name: "Vlad Lenox Hill CT"
        value_template: "{{ as_timestamp('2021-04-03 08:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-04-03 08:00:00-04:00'
          end_time: '2021-04-03 09:00:00-04:00'
      event_appointments_echo:
        friendly_name: "Vlad Lenox Hill Echo"
        value_template: "{{ as_timestamp('2021-04-09 11:25:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-04-09 11:25:00-04:00'
          end_time: '2021-04-09 12:25:00-04:00'
      event_vacation_vlad_inna:
        friendly_name: "Vlad Inna Vacation"
        value_template: "{{ as_timestamp('2021-06-14') | timestamp_local }}"
        device_class: "timestamp"
      event_vacation_vlad_inna_1:
        friendly_name: "Vlad Inna Vacation"
        value_template: "{{ as_timestamp('2021-06-15') | timestamp_local }}"
        device_class: "timestamp"
      event_classes_sql:
        friendly_name: "SQL Class"
        value_template: "{{ as_timestamp('2021-12-12 13:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-12-12 13:00:00-05:00'
          end_time: '2021-12-12 15:30:00-05:00'
      event_classes_sql_1:
        friendly_name: "SQL Class"
        value_template: "{{ as_timestamp('2021-12-19 13:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-12-19 13:00:00-05:00'
          end_time: '2021-12-19 15:30:00-05:00'
```

![calendar](https://user-images.githubusercontent.com/30022288/230461114-0ac4dc71-7900-442e-a4e9-2ae1d6faecd3.png)

**Comment by vlad36N** [comment] 2023-04-06 20:28
This is errors from log:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/entities_calendar/calendar.py:231
Integration: entities_calendar (documentation, issues)
First occurred: 12:55:29 PM (3 occurrences)
Last logged: 3:28:40 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 525, in get
    calendar_event_list = await entity.async_get_events(
  File "/config/custom_components/entities_calendar/calendar.py", line 183, in async_get_events
    return await self.data.async_get_events(hass, start_date, end_date)
  File "/config/custom_components/entities_calendar/calendar.py", line 231, in async_get_events
    end = start + timedelta(days=1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345
First occurred: 12:38:05 PM (1374 occurrences)
Last logged: 4:26:08 PM

Update for calendar.appointments fails
Update for calendar.birthdays fails
Update for calendar.memorable fails
Update for calendar.vacation fails
Update for calendar.classes fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 275, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

**Comment by gateriderz** [comment] 2023-04-07 18:16
Hi @vlad36N , this was an attempt on my part to workaround the issue, but I believe it needs more knowledgeable programmer to review all the proper code.

If it doesn't work for you, I would recommend waiting for @gadgetchnnel  to take a look at the integration.

Thanks

**Comment by gadgetchnnel** [comment] 2023-04-07 18:31
I've just pushed a beta version of this, 0.0.10b0, which include fixes for the validation changes in 2023.4
(There was also and issue where it would wrongly detect the start and end times of an event having different timezones, and this should also fix that).

Can you please try with this (you may need to enable Beta releases in HACS if you use that) and let me know if it works for you?

**Comment by gateriderz** [comment] 2023-04-07 19:21
Tested beta and rebooted.
No more errors on my side (i have 5 calendars loaded).

Thank you

**Comment by vlad36N** [comment] 2023-04-07 20:22
Installed beta and rebooted.

Have only one error:

Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345
First occurred: 4:12:03 PM (4 occurrences)
Last logged: 4:15:03 PM

**Update for calendar.appointments fails**
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2022-05-07 07:50:00-04:00, 2021-05-07 07:50:00-04:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2022-05-07 07:50:00-04:00, 2021-05-07 07:50:00-04:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 176, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 285, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2022-05-07 07:50:00-04:00, 2021-05-07 07:50:00-04:00)

**But all calendars loaded, including appointments**

**Thank you**

![appointments](https://user-images.githubusercontent.com/30022288/230673779-cdd968fa-cd8f-4aad-9b33-f2111ba77d02.png)

**Comment by codyc1515** [comment] 2023-04-26 09:07
Beta worked for me. Should be okay to push out.

**Comment by vlad36N** [comment] 2023-05-29 13:35
Hi @gadgetchnnel. 
I figure it out. 
Error "Expected positive event duration" is legit. I  have more then 1000 calendar events and problem is events with start datetime and end datetime, but not for all day event. I did found couple events which has end date before start date and end time before or equal start time. Ones I fixed all date and time no more errors occurs. 
Please close issue.
Thank you.

**Comment by gadgetchnnel** [comment] 2023-05-29 14:53
Closed as resolved

**Closed as completed by gadgetchnnel** 2023-05-29 14:53 UTC
